description: >
  Sets a single Skpr config from an environment.

parameters:
  docker_image:
    default: "skpr/cli:latest"
    description: "The Skpr CLI version tag"
    type: string
  env:
    type: string
    description: "The app environment"
  key:
    type: string
    description: "The config key to set"
  value:
    type: string
    description: "The configuration value to assign to the input key"

steps:
  - run:
      name: "Skpr Config (Set '<<parameters.key>>')"
      command: |
        echo "Setting Skpr config for '<<parameters.key>>' on <<parameters.env>>"
        docker run --rm \
          -v "$(pwd):$(pwd)" \
          -w "$(pwd)" \
          -e SKPR_USERNAME=${SKPR_USERNAME} \
          -e SKPR_PASSWORD=${SKPR_PASSWORD} \
          <<parameters.docker_image>> \
          skpr config set --force <<parameters.env>> <<parameters.key>> <<parameters.value>>
