description: >
  Packages an app for deployment.

parameters:
  version:
    type: string
    default: ""
    description: "The app version"
  workdir:
    type: string
    default: ""
    description: "Working directory of skpr project"

steps:
  - run:
      environment:
        PARAM_VERSION: <<parameters.version>>
        SKPR_WORKDIR: <<parameters.workdir>>
      name: Skpr Package
      command: <<include(scripts/package.sh)>>
