description: >
  Packages an app for deployment.

parameters:
  docker_image:
    default: "skpr/cli:latest"
    description: "The Skpr CLI version tag"
    type: string
  version:
    type: string
    default: ""
    description: "The app version"

steps:
  - run:
      environment:
        SKPR_CLI_DOCKER_IMAGE: <<parameters.docker_image>>
        PARAM_VERSION: <<parameters.version>>
      name: Skpr Package
      command: <<include(scripts/package.sh)>>
