description: >
  Configure the settings file for a StackHawk scan.

parameters:
  env:
    type: string
    default: "CI"
    description: "The environment to view the dataset on in StackHawk's interface."
  id:
    type: string
    default: ""
    description: "The ID of the application you're intending to scan using StackHawk."
  host:
    type: string
    default: "CI"
    description: "The endpoint which will be scanned by StackHawk."
  paths:
    type: string
    default: "['/']"
    description: "Paths as a list in JSON format contained in single quotes ('') or escaped double quotes (\"\"). Example: ['/', '/my/example/content']"

steps:
  - run:
      environment:
        PARAM_ENV: <<parameters.env>>
        PARAM_ID: <<parameters.id>>
        PARAM_HOST: <<parameters.host>>
        PARAM_PATHS: <<parameters.paths>>
      name: "StackHawk: Configure"
      command: <<include(scripts/stackhawk_configure.sh)>>
